# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build .NET

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies - API
      run: dotnet restore
      working-directory: src/CadCli.Api
      
    - name: Restore dependencies - Tests
      run: dotnet restore
      working-directory: src/CadCli.Tests
      
    - name: Build - API
      run: dotnet build --no-restore
      working-directory: src/CadCli.Api
      
    - name: Test
      run: dotnet test --verbosity normal
      working-directory: src/CadCli.Tests
      
    - name: Publish
      run: dotnet publish -c Release -o myap
      working-directory: src/CadCli.Api
